// Stub TypeScript type file for Supabase database schema.
// This will be auto-generated by: supabase gen types typescript --project-id <id>
// Run: pnpm supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          billing_tier: 'FREE' | 'PRO'
          notion_access_token: string | null
          notion_workspace_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['users']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['users']['Insert']>
      }
      sessions: {
        Row: {
          id: string
          user_id: string
          title: string | null
          video_url: string | null
          video_title: string | null
          notes: string | null
          state: 'RECORDING' | 'COMPLETED' | 'POST_PROCESSING'
          duration_seconds: number | null
          notion_page_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: Omit<Database['public']['Tables']['sessions']['Row'], 'created_at' | 'updated_at'>
        Update: Partial<Database['public']['Tables']['sessions']['Insert']>
      }
      session_chunks: {
        Row: {
          id: string
          session_id: string
          transcript: string
          extracted_notes: string | null
          chunk_index: number
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['session_chunks']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['session_chunks']['Insert']>
      }
      flashcards: {
        Row: {
          id: string
          session_id: string
          front: string
          back: string
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['flashcards']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['flashcards']['Insert']>
      }
      screenshots: {
        Row: {
          id: string
          session_id: string
          storage_path: string
          caption: string | null
          inserted_at_chunk: number | null
          created_at: string
        }
        Insert: Omit<Database['public']['Tables']['screenshots']['Row'], 'created_at'>
        Update: Partial<Database['public']['Tables']['screenshots']['Insert']>
      }
    }
    Views: Record<string, never>
    Functions: Record<string, never>
    Enums: {
      billing_tier: 'FREE' | 'PRO'
      session_state: 'RECORDING' | 'COMPLETED' | 'POST_PROCESSING'
    }
  }
}
