// Stub TypeScript type file for Supabase database schema.
// This will be auto-generated by: supabase gen types typescript --project-id <id>
// Run: pnpm supabase gen types typescript --project-id YOUR_PROJECT_ID > src/types/supabase.ts

export type Database = {
  public: {
    Tables: {
      users: {
        Row: {
          id: string
          email: string
          full_name: string | null
          avatar_url: string | null
          billing_tier: 'FREE' | 'PRO'
          free_minutes_used: number
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          notion_access_token: string | null
          notion_workspace_id: string | null
          notion_workspace_name: string | null
          notion_database_id: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          full_name?: string | null
          avatar_url?: string | null
          billing_tier?: 'FREE' | 'PRO'
          free_minutes_used?: number
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          notion_access_token?: string | null
          notion_workspace_id?: string | null
          notion_workspace_name?: string | null
          notion_database_id?: string | null
        }
        Update: {
          id?: string
          email?: string
          full_name?: string | null
          avatar_url?: string | null
          billing_tier?: 'FREE' | 'PRO'
          free_minutes_used?: number
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          notion_access_token?: string | null
          notion_workspace_id?: string | null
          notion_workspace_name?: string | null
          notion_database_id?: string | null
          updated_at?: string
        }
        Relationships: []
      }
      sessions: {
        Row: {
          id: string
          user_id: string
          title: string
          notes: string
          state: 'RECORDING' | 'PAUSED' | 'COMPLETED' | 'POST_PROCESSING'
          duration_seconds: number
          watch_time_seconds: number
          notion_page_id: string | null
          video_url: string | null
          video_title: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          title?: string
          notes?: string
          state?: 'RECORDING' | 'PAUSED' | 'COMPLETED' | 'POST_PROCESSING'
          duration_seconds?: number
          watch_time_seconds?: number
          notion_page_id?: string | null
          video_url?: string | null
          video_title?: string | null
        }
        Update: {
          id?: string
          user_id?: string
          title?: string
          notes?: string
          state?: 'RECORDING' | 'PAUSED' | 'COMPLETED' | 'POST_PROCESSING'
          duration_seconds?: number
          watch_time_seconds?: number
          notion_page_id?: string | null
          video_url?: string | null
          video_title?: string | null
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'sessions_user_id_fkey'
            columns: ['user_id']
            referencedRelation: 'users'
            referencedColumns: ['id']
          }
        ]
      }
      session_chunks: {
        Row: {
          id: string
          session_id: string
          transcript: string
          chunk_index: number
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          transcript: string
          chunk_index: number
        }
        Update: {
          id?: string
          session_id?: string
          transcript?: string
          chunk_index?: number
        }
        Relationships: [
          {
            foreignKeyName: 'session_chunks_session_id_fkey'
            columns: ['session_id']
            referencedRelation: 'sessions'
            referencedColumns: ['id']
          }
        ]
      }
      flashcards: {
        Row: {
          id: string
          session_id: string
          front: string
          back: string
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          front: string
          back: string
        }
        Update: {
          id?: string
          session_id?: string
          front?: string
          back?: string
        }
        Relationships: [
          {
            foreignKeyName: 'flashcards_session_id_fkey'
            columns: ['session_id']
            referencedRelation: 'sessions'
            referencedColumns: ['id']
          }
        ]
      }
      screenshots: {
        Row: {
          id: string
          session_id: string
          data_url: string
          analysis: string | null
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          data_url: string
          analysis?: string | null
        }
        Update: {
          id?: string
          session_id?: string
          data_url?: string
          analysis?: string | null
        }
        Relationships: [
          {
            foreignKeyName: 'screenshots_session_id_fkey'
            columns: ['session_id']
            referencedRelation: 'sessions'
            referencedColumns: ['id']
          }
        ]
      }
      action_plans: {
        Row: {
          id: string
          session_id: string
          content: string
          created_at: string
        }
        Insert: {
          id?: string
          session_id: string
          content: string
        }
        Update: {
          id?: string
          session_id?: string
          content?: string
        }
        Relationships: [
          {
            foreignKeyName: 'action_plans_session_id_fkey'
            columns: ['session_id']
            referencedRelation: 'sessions'
            referencedColumns: ['id']
          }
        ]
      }
    }
    Views: Record<string, never>
    Functions: {
      increment_free_minutes: {
        Args: {
          p_user_id: string
          p_minutes: number
        }
        Returns: undefined
      }
    }
    Enums: {
      billing_tier: 'FREE' | 'PRO'
      session_state: 'RECORDING' | 'PAUSED' | 'COMPLETED' | 'POST_PROCESSING'
    }
    CompositeTypes: Record<string, never>
  }
}
